# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: zeed
before:
  hooks:
    - go mod download
builds:
  - id: 'zeed-build-linux-windows'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: 'zeed-build-darwin'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - "LICENSE"
      - "CHANGELOG.md"
      - "README.md"
      - "UPGRADE.md"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"
release:
  mode: replace
notarize:
  macos:
    -
      enabled: '{{ isEnvSet "APPLE_SIGN_P12" }}'
      ids:
        - zeed-build-darwin
      sign:
        certificate: "{{ .Env.APPLE_SIGN_P12 }}"
        password: "{{ .Env.APPLE_SIGN_P12_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.APPLE_NOTARY_ISSUER }}"
        key_id: "{{ .Env.APPLE_NOTARY_KEY_ID }}"
        key: "{{ .Env.APPLE_NOTARY_KEY }}"
        wait: false
